version: '3.8'  # Specify the version of Docker Compose

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - collaborativenetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - collaborativenetwork
  
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: always
    ports:
      - "9000:9000"  # Expose Kafdrop UI on port 9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092  # Internal address for Kafka
    depends_on:
      - kafka
    networks:
      - collaborativenetwork


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"        # Internal communication port
      - "29092:29092"      # External access port for localhost
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - collaborativenetwork


  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ./services/backend:/app
      - /app/node_modules  # Prevent overwriting node_modules inside the container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - kafka  # Ensure Kafka is started before backend
    networks:
      - collaborativenetwork

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./services/frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules inside the container
    ports:
      - "3000:3000"
    networks:
      - collaborativenetwork

networks:
  collaborativenetwork:
    name: collaborativenetwork
    driver: bridge
