name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Make install
      run: |
        sudo apt install make

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install vm-tool

    - name: Deploy to VM
      run: |
        python ./scripts/deploy_to_vm.py
